### ISSUE TITLE
[1.16.1] Datapacks not loading, need to do /reload in order for them to work.

### ISSUE THREAD

**Issue by Gbergz** [DarkRoleplay/DRP---Global-Data-Pack#2]
Title^

**Minecraft:** 1.16.1
**Forge:** 32.0.75
**Mod Version:** [1.4.1](https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack/files/2990971)

Any ideas?
Would love to use this mod but if they don't load without a reload it's like not using this mod at all.

**-** Gbergz

**Comment by JTK222** [comment]
Fixed in v1.4.2 thanks for reporting that issue.
The "fix" to this is reloading the datapacks after the global ones were added.
Sadly Mojang moved the code that loads datapacks and I didn't notice it. 
Which now presents the issue that I cannot insert additional datapacks before they get loaded.
To properly fix this I'd need a core mod, but as the performance hit only happens once on world load, I hope it's a okish solution for now.
